import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import { MapProvider } from "@/context/map/mapContext";
import { AuthContextProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthContextProvider>
      <html lang="en" dir="rtl">
        <body className="flex flex-col h-screen relative">
          <MapProvider>
            <Navbar />
            {children}
          </MapProvider>
        </body>
      </html>
    </AuthContextProvider>
  );
}
